// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Player } from "./Player";
import type { Point } from "./Point";

export type Curve = { points: Array<Point>, author: Player, };
