// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoteFakeEvent } from "./VoteFakeEvent";

export type EventIn = { "type": "VoteFake" } & VoteFakeEvent;
