// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrawEvent } from "./DrawEvent";
import type { JoinEvent } from "./JoinEvent";
import type { NextTurnEvent } from "./NextTurnEvent";
import type { VotesTotalEvent } from "./VotesTotalEvent";

export type EventOut = { "type": "JoinEvent" } & JoinEvent | { "type": "NextTurn" } & NextTurnEvent | { "type": "DrawEvent" } & DrawEvent | { "type": "VoteFake" } & VotesTotalEvent;
